[project]
name = "pd_ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psycopg-pool>=3.2.6",
    "psycopg[binary]>=3.2.5",
    "pydantic-ai>=0.0.32",
    "python-dotenv>=1.0.1",
]
